### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by teackot** [Harshit-T/nightly#2]
Cool, but there is a typo in the logo.svg

**Comment by Harshit-T** [comment]
Can you specify what typo?

**Comment by teackot** [comment]
Right in README.md

**Comment by Harshit-T** [comment]
Must be an issue with your fonts. There is no typo on my side.

**Comment by Harshit-T** [comment]
![logo](https://user-images.githubusercontent.com/89409201/156305344-d8e9308b-93b5-4c96-a93f-838ea125c51c.svg)
